environment: production

run.config:
  # add nginx package
  extra_packages:
    - nginx




user: root
group: root
port: 4567
pid: tmp/pids/thin.pid
timeout: 30
wait: 30
log: /var/log/thin/thin.log
max_conns: 1024
require: []
environment: production
max_persistent_conns: 512
servers: 2
onebyone: true
threaded: true
no-epoll: true
daemonize: true
socket: tmp/sockets/thin.sock
chdir: /var/www/example.com/public_html
tag: example aux
environment: production
chdir: /path/to/my/app
address: 127.0.0.1
rackup: /path/to/my/app/config.ru
log: /path/to/my/app/thin.log


